### ISSUE TITLE
textlint's demo site

### ISSUE THREAD

**Issue by azu** [textlint/textlint.github.io#1]
We want to create textlint's online demo site.

Simple [Holy Grail Layout](https://philipwalton.github.io/solved-by-flexbox/demos/holy-grail/).

First step
1. online demo and show github link.

Edit: 2016-02-05
## Concept

This site is for demo and describing concept(rule and extensible) of textlint.

[![Precursor](https://precursorapp.com/document/Untitled-17592202908138.svg?auth-token=)](https://precursorapp.com/document/Untitled-17592202908138)

**Comment by azu** [comment]
- [x] How to deploy

Deploy by Travis CI

**Comment by azu** [comment]
![textlint 2016-01-27 20-35-03](https://cloud.githubusercontent.com/assets/19714/12612369/80252c9c-c535-11e5-93ed-3c67ac8a6a3e.png)

use flexbox

**Comment by azu** [comment]
![website-mock](https://cloud.githubusercontent.com/assets/19714/12647339/01b00a38-c618-11e5-87c9-29a2f552c410.png)

mock design.

**Comment by azu** [comment]
Current:
![textlint 2016-01-31 23-47-00](https://cloud.githubusercontent.com/assets/19714/12702761/f113892a-c874-11e5-860f-15565fda12d1.png)

**Comment by uetchy** [comment]
looks nice!

**Comment by azu** [comment]
I'v set up to deploy script.
http://textlint.github.io/

**Comment by azu** [comment]
Add textlint's philosophy.

![screen shot 2016-02-15 at 00 08 51](https://cloud.githubusercontent.com/assets/19714/13034416/55b18c34-d378-11e5-9e0c-8ca31b675142.png)

**Comment by azu** [comment]
close by https://github.com/textlint/textlint/pull/114
